style: github
template: CHANGELOG.tpl.md
info:
  title: "CHANGELOG"

options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - chore
        - others
  commit_groups:
    https://github.com/laziness-coders/mongostore.git:
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      chore: Chores
      others: Others
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE