name: Goreleaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
#      -
#        name: Set up Go
#        uses: actions/setup-go@v5.0.2
#        with:
#          go-version: 1.22
#      # -
        # name: Run GoReleaser
        # uses: goreleaser/goreleaser-action@v2
        # with:
        #   # either 'goreleaser' (default) or 'goreleaser-pro'
        #   distribution: goreleaser
        #   version: latest
        #   args: release --rm-dist
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Install git-chglog
        run: |
            wget https://github.com/git-chglog/git-chglog/releases/download/v0.15.1/git-chglog_0.15.1_linux_amd64.tar.gz
            tar -xzf git-chglog_0.15.1_linux_amd64.tar.gz
            sudo mv git-chglog /usr/local/bin/

      -
        name: Generate Changelog
        run: git-chglog -c .chglog/config.yml -o CHANGELOG.md

      -
        name: Read Changelog
        id: changelog
        run: echo "::set-output name=changelog::$(cat CHANGELOG.md)"

      - 
        name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          tag: ${{ github.ref_name }}
          draft: true
          prerelease: false